name: Build pull request

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
    - "!master"

jobs:
  build_oh3:
    strategy:
      fail-fast: false
      matrix:
        java: [ '11' ]
        maven: [ '3.8.4' ]
        os: [ 'ubuntu-20.04' ]
    name: Build OH3 (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.java }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.java }}-maven-

    - name: Downgrade version
      run: mvn versions:set -DnewVersion=3.4.4-SNAPSHOT
    - name: Downgrade parent version
      run: mvn versions:update-parent -DskipResolution=true -DparentVersion=3.4.4
    - name: Build
      run: mvn -P 'oh3' -P 'standalone' --batch-mode -DskipChecks -Doh.java.version=11 clean verify

  build_oh4:
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        maven: [ '3.8.4' ]
        os: [ 'ubuntu-20.04' ]
    name: Build OH4 (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.java }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.java }}-maven-

    - name: Build
      run: mvn -P 'standalone' --batch-mode -DskipChecks -Doh.java.version=17 clean verify
